# Generated by Django 6.0.5 on 2026-05-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=200)),
                ('workload', models.CharField(max_length=50)),
                ('assessment_type', models.CharField(max_length=50)),
                ('peer', models.FloatField(default=0.0)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_by', to='SkillPath.course')),
                ('skills', models.ManyToManyField(blank=True, related_name='courses', to='SkillPath.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('courses', models.ManyToManyField(blank=True, related_name='career', to='SkillPath.course')),
                ('skills', models.ManyToManyField(blank=True, related_name='career', to='SkillPath.skill')),
            ],
        ),
    ]
