# Generated by Django 6.0.5 on 2026-05-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillPath', '0002_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('data', 'Data & Analysis'), ('technical', 'Technical'), ('research', 'Research & Communication'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
